### ISSUE TITLE
Tasks.sh does not exist

### ISSUE THREAD

**Issue by Wataru-Nakata** [Comet0322/MiniSUPERB#1]
Hi! thank you for nice code.
I found that the `minisuperb/Tasks.sh` does not exist even though you mention it in your README
How can I runt the experiment?

**Comment by Wataru-Nakata** [comment]
I actually now understand that the Task supposed to be replaced with ss, asr etc.. 
Is this understanding correct?

**Comment by Comet0322** [comment]
You're right. Sorry for the poor explanation, it's fixed now.

**Comment by Wataru-Nakata** [comment]
Thanks you for addressing this issue. I really apreciate it
